# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

QT += core gui network qml quick quickwidgets serialport sql widgets xml

TEMPLATE = app
TARGET = QIAGVSSApplication
DESTDIR = ../../x64/Debug
CONFIG += debug
LIBS += -L"./res/led/-lEQ2008_Dll"
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += ./GeneratedFiles
include(QIAGVSSApplication.pri)
